### ISSUE TITLE
nettle-0.1.0 doesn't compile against nettle 3.0

### ISSUE THREAD

**Issue by peti** [stbuehler/haskell-nettle#6]
Citing from http://hydra.cryp.to/build/724099/nixlog/2/raw:

    Building nettle-0.1.0...
    Preprocessing library nettle-0.1.0...
    In file included from ForeignImports.hsc:108:0:
    src/nettle-ciphers.h:43:22: error: field ‘encrypt’ has incomplete type
      struct camellia_ctx encrypt, decrypt;
                          ^
    src/nettle-ciphers.h:43:31: error: field ‘decrypt’ has incomplete type
      struct camellia_ctx encrypt, decrypt;
                                   ^
    compiling dist/build/Crypto/Nettle/Ciphers/ForeignImports_hsc_make.c failed (exit code 1)

**Comment by stbuehler** [comment]
Yes, there were some API changes in nettle; I'll need to have a look and think about whether it is possible to support multiple nettle versions.

**Comment by nomeata** [comment]
This also affects Debian: https://buildd.debian.org/status/package.php?p=haskell-nettle&suite=sid

**Comment by stbuehler** [comment]
The current master should now build against nettle 3 (but not 2.x anymore); no release yet.

I'm not sure though I should continue this project given the state of http://hackage.haskell.org/package/cryptonite - even crypto-cipher-types (which haskell-nettle depends on) got moved into the huge bundle now.

**Comment by clinty** [comment]
https://github.com/vincenthz/cryptonite does not have CAST5 and it does not have Twofish

**Comment by stbuehler** [comment]
I see :) Any opinions what I should do about the crypto-cipher-types dependency? Leave it as it is, switch to cryptonite, or remove it and copy the classes?

**Comment by clinty** [comment]
Since I'm going to end up needing cryptonite BlockCipher instances for those two ciphers before too long, you switching to cryptonite would be best for me.

**Comment by clinty** [comment]
Or how about crypto-api instead?

**Comment by peti** [comment]
Is there any chance that support for nettle 3.x becomes available? http://hackage.haskell.org/package/hOpenPGP without nettle.

**Comment by stbuehler** [comment]
@clinty @peti I had support for 3.x in HEAD for a long time, so I guess I should just go forward and push a release. For now there is http://hackage.haskell.org/package/nettle-0.2.0/candidate - maybe you could test whether this works for you before I release it.

**Comment by clinty** [comment]
Appears to work fine for me.

**Comment by stbuehler** [comment]
haskel-nettle-0.2.0 supports nettle 3.1.

The crypto-cipher-types dependency issue is tracked in #7
